language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TEST_TARGET=default
    - python: 3.6
      env: TEST_TARGET=coding_standards
  allow_failures:
    - python: 3.6
      env: TEST_TARGET=coding_standards

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-test.txt
  - source activate TEST

script:
  - set -e

  - if [[ $TEST_TARGET == "default" ]]; then
      py.test -rxs --verbose ;
    fi

  - if [[ $TEST_TARGET == "coding_standards" ]]; then
      py.test --verbose --flake8 -m flake8 -q ;
    fi
