language: python
python:
  - "2.7"
before_install:
  # System packages
  - sudo apt-get update -qq

  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget ${CONDA_BASE}-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget ${CONDA_BASE}3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

install:
  # Customise the testing environment
  # ---------------------------------
  - conda install --channel ioos --file requirements.txt
  - conda install --channel ioos "Django>=1.7,<1.8"
  - conda install --channel ioos --file requirements-dev.txt
  - conda install --channel ioos --file requirements-test.txt
  - conda install --channel ioos django-debug-toolbar
  - conda list --export

script: py.test -rxs --verbose
