name: sciwmsdev37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - argh=0.26.2
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cftime=1.0.3.4
  - cmocean=2.0
  - curl=7.64.1
  - cycler=0.10.0
  - cython=0.29.6
  - dbus=1.13.2
  - dj-static=0.0.6
  - django=2.1.8
  - django-autoslug=1.9.4
  - django-debug-toolbar=1.10.1
  - django-extensions=2.1.6
  - django-grappelli=2.12.2
  - django-typed-models=0.9.0
  - djangorestframework=3.9.2
  - entrypoints=0.3
  - esmf=7.1.0
  - expat=2.2.5
  - flake8=3.7.7
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.56.2
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - huey=1.10.5
  - icu=58.2
  - isodate=0.6.0
  - jpeg=9c
  - jsonfield=2.0.2
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libspatialindex=1.9.0
  - libssh2=1.8.2
  - libstdcxx-ng=8.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=2.2.3
  - matplotlib-base=2.2.3
  - mccabe=0.6.1
  - more-itertools=4.3.0
  - mpi=1.0
  - mpich=3.2.1
  - nco=4.7.9
  - ncurses=6.1
  - netcdf-fortran=4.4.5
  - netcdf4=1.5.0.1
  - numpy=1.16.2
  - openblas=0.3.5
  - openssl=1.1.1b
  - pandas=0.24.2
  - pathtools=0.1.2
  - pcre=8.43
  - peewee=3.6.4
  - pip=19.0.3
  - pluggy=0.9.0
  - proj4=5.2.0
  - pthread-stubs=0.4
  - py=1.8.0
  - pyaxiom=1.4.6
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pyinotify=0.9.6
  - pyncml=0.0.9
  - pynco=1.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyqt=5.6.0
  - pysgrid=0.3.5
  - pystache=0.5.4
  - pytest=4.4.0
  - pytest-django=3.4.8
  - pytest-env=0.6.2
  - pytest-flake8=1.0.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyugrid=0.3.1
  - pyyaml=5.1
  - qt=5.6.3
  - readline=7.0
  - redis-py=3.2.1
  - rtree=0.8.3
  - scipy=1.2.1
  - setuptools=41.0.0
  - simplejson=3.16.0
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - sqlparse=0.3.0
  - static=1.1.1
  - tk=8.6.9
  - tornado=6.0.2
  - typing=3.6.4
  - udunits2=2.2.27.6
  - utide=0.2.2
  - watchdog=0.8.3
  - werkzeug=0.15.2
  - wheel=0.33.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
