name: sciwmsprod37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.14.0
  - cftime=1.1.1.2
  - cmocean=2.0
  - colorspacious=1.1.2
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - cython=0.29.16
  - dbus=1.13.6
  - dj-static=0.0.6
  - django=2.2.8
  - django-autoslug=1.9.4
  - django-grappelli=2.14.1
  - django-redis-cache=2.0.0
  - django-typed-models=0.9.0
  - djangorestframework=3.11.0
  - dnspython=1.16.0
  - ecdsa=0.13
  - esmf=8.0.0
  - eventlet=0.25.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - gmp=6.2.0
  - greenlet=0.4.15
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gunicorn=20.0.4
  - hdf4=4.2.13
  - hdf5=1.10.5
  - hiredis=1.0.1
  - huey=2.1.3
  - icu=64.2
  - idna=2.9
  - isodate=0.6.0
  - jpeg=9c
  - jsonfield=3.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.3
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - monotonic=1.5
  - nco=4.9.2
  - ncurses=6.1
  - netcdf-fortran=4.5.2
  - netcdf4=1.5.3
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - openssl=1.1.1e
  - pandas=1.0.3
  - pcre=8.44
  - pip=20.0.2
  - proj4=5.2.0
  - psycopg2=2.8.4
  - pthread-stubs=0.4
  - pyaxiom=1.4.6
  - pycparser=2.20
  - pycryptodome=3.9.7
  - pyncml=0.0.9
  - pynco=1.0.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=1.9.6
  - pyqt=5.12.3
  - pysgrid=0.3.5
  - pystache=0.5.4
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pyugrid=0.3.1
  - qt=5.12.5
  - readline=8.0
  - redis-py=3.4.1
  - rtree=0.9.4
  - scipy=1.4.1
  - setproctitle=1.1.10
  - setuptools=46.1.3
  - simplejson=3.17.0
  - six=1.14.0
  - sqlite=3.30.1
  - sqlparse=0.3.1
  - static=1.1.1
  - tempest-remap=2.0.3
  - tk=8.6.10
  - tornado=6.0.4
  - udunits2=2.2.27.6
  - utide=0.2.5
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
